### ISSUE TITLE
Make icons accessible

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/radix-icons#19]
Hey ✌️

I noticed that none of the icons have a `<title>` element inside the `<svg>`, which acts as alternative text for screen readers. It would be great to add something like this for the generated icons:

```tsx
<svg aria-labelledby="arrowLeftIcon">
  <title id="arrowLeftIcon">Arrow left icon</title>
   // actual svg implementation
</svg>
```

I think there would have to be some changes made to the [generate-icon-lib](https://github.com/modulz/radix-icons/tree/master/packages/generate-icon-lib) package, which I'm happy to do with some direction!

**Comment by vladmoroz** [comment]
Hey Rauno 👋
We decided in favour of another approach when alternative text is provided at the consumer level.

There's a few advantages to alternative text at consumer level over labelling icons with a `<title>` element. For example, at icon package level we only know that icons have titles like "Pencil", "Arrow Left", "Gear", while at app level these icons might represent actions like "Edit", "Go Back", "Open Settings", etc. in a specific context. And ideally, icons should be accompanied by a visible text label anyway, which would make alternative text redundant.

Ultimately, we plan to open up an `AccessibleIcon` primitive that adds visually hidden text for unlabelled icons.
Thanks for raising this and sorry I haven't responded earlier! Hope this makes sense.
