### ISSUE TITLE
Using react-figma

### ISSUE THREAD

**Issue by ilyalesik** [modulz/radix-icons#33]
Hi! It's possible to use [react-figma](https://github.com/react-figma/react-figma) for creating universal react components that can be used on Figma (rendering icons to document through plugin) and on the web. I can make PR if are you interested.

**Comment by colmtuite** [comment]
What would the benefit of rendering from React to Figma be?

We already have the icons in a Figma file, that acts as the source of truth. When the icons are updated in Figma, we run a script which converts them into React components.

I can't see any benefit in going the other way around?

**Comment by ilyalesik** [comment]
It's could be useful only if you want to use a different approach - code as a source of truth. So, I see that you not need it and close the issue. 🙌
