### ISSUE TITLE
Improve bundle size when only using a few icons

### ISSUE THREAD

**Issue by rafgraph** [modulz/radix-icons#39]
Hi, great set of icons, however `npm install @modulz/radix-icons` and `import { SunIcon } from '@modulz/radix-icons';` (using just 1 icon) adds 75KB to the production build (using create react app). This makes them kind of unusable as an npm install.

Consider making each icon its own file in the build process so can do something like `import { SunIcon } from '@modulz/radix-icons/sun-icon';`

**Comment by vladmoroz** [comment]
Hey, thanks for the report. This shouldn't happen, we will look into improving the bundle size with individual icons.

**Comment by vladmoroz** [comment]
@rafgraph we released 3.2.0 fixing this issue 🎉

**Comment by rafgraph** [comment]
Thanks @vladmoroz, I can confirm it works.

I don't know if you're taking requests for icons, but it would be great to have a data graph icon. There is a `Table` icon which I can use for data in table format, and it'd be great to have a corresponding data in graph format icon (maybe something with lines or bars).

**Comment by peduarte** [comment]
@rafgraph yep, we're open to requests! Can you create an issue? Cheers 🤜
